import { NakshraProduct } from "@nakshra/shared-types/product";

export const DEFAULT_PRODUCTS: NakshraProduct[] = [
  {
    id: 1,
    slug: "bagla-mukhi-yantra",
    name: "Bagla Mukhi Yantra",
    subtitle: "24K Gold Plated",
    category: "Yantra",
    purpose: "Protection",
    price: 599,
    original: 899,
    rating: 4.8,
    reviews: 312,
    img: "https://cdn.shopify.com/s/files/1/0878/4907/4985/files/1_23.jpg?v=1782120393",
    badges: ["Temple Energized", "Bestseller"],
    shortDesc: "Stambhan · Vijay · Raksha. Controls negativity, brings victory in legal matters and protects from enemies.",
    benefits: ["Victory in Legal Matters", "Protection From Enemies", "Increases Confidence", "Improves Communication"],
    size: "3.5 cm x 3.5 cm",
    material: "Metal (Golden Finish)",
    useFor: ["Pendant", "Pocket", "Wallet", "Car", "Pooja Sthal"],
    stock: 100
  },
  {
    id: 2,
    slug: "love-money-metal-bracelet",
    name: "Love & Money Metal Bracelet",
    subtitle: "Triple Metal Synergy",
    category: "Bracelets",
    purpose: "Wealth & Harmony",
    price: 1999,
    original: 2999,
    rating: 4.9,
    reviews: 428,
    img: "https://cdn.shopify.com/s/files/1/0878/4907/4985/files/1-1_f53e2d9e-40a0-4f0e-95a9-8d6a878b2f77.webp?v=1781163169",
    badges: ["Trending", "Temple Energized"],
    shortDesc: "Crafted from pure copper, brass and silver to align planetary energy for love and wealth.",
    benefits: ["Attracts Prosperity", "Strengthens Relationships", "Removes Negative Energy"],
    size: "Adjustable",
    material: "Copper, Brass & Silver",
    useFor: ["Daily Wear", "Gifting", "Meditation"],
    stock: 75
  },
  {
    id: 3,
    slug: "citrine-sun-ring",
    name: "Citrine Sun Ring",
    subtitle: "Natural Kundali Energized Gem",
    category: "Gemstone",
    purpose: "Jupiter Energy",
    price: 2499,
    original: 3499,
    rating: 4.7,
    reviews: 189,
    img: "https://cdn.shopify.com/s/files/1/0878/4907/4985/files/Artboard1_19.webp?v=1782733204",
    badges: ["Vedic Certified", "Gold Plated"],
    shortDesc: "Unlocks wisdom, mental clarity and commercial success under Guru's cosmic blessing.",
    benefits: ["Boosts Career & Business", "Enhances Intellect", "Brings Abundance"],
    size: "Resizable Ring",
    material: "Natural Citrine & Silver Alloy",
    useFor: ["Index Finger", "Pooja Rituals"],
    stock: 40
  },
  {
    id: 4,
    slug: "nepal-1-mukhi-rudraksha",
    name: "Nepal Origin 1 Mukhi Rudraksha",
    subtitle: "Certified Half-Moon Shape",
    category: "Rudraksha",
    purpose: "Shiva Power",
    price: 2999,
    original: 4999,
    rating: 5.0,
    reviews: 512,
    img: "https://cdn.shopify.com/s/files/1/0878/4907/4985/files/1_a144e37f-680e-430f-80bd-e7c35b9d2ebb.webp?v=1759924225",
    badges: ["Rare Collectible", "Lab Certified"],
    shortDesc: "The supreme bead of Lord Shiva granting enlightenment, focus and ultimate mental peace.",
    benefits: ["Destroys Past Karma", "Grants Extreme Focus", "Removes Fear & Anxiety"],
    size: "22-26mm",
    material: "100% Genuine Nepalese Bead",
    useFor: ["Neck Pendant", "Meditation Altar"],
    stock: 20
  },
  {
    id: 5,
    slug: "pyrite-sun-ring",
    name: "Pyrite Sun Ring",
    subtitle: "Fool's Gold Power Ring",
    category: "Gemstone",
    purpose: "Wealth & Protection",
    price: 1799,
    original: 2499,
    rating: 4.8,
    reviews: 210,
    img: "https://cdn.shopify.com/s/files/1/0878/4907/4985/files/Artboard1_18.webp?v=1782199970",
    badges: ["Popular", "Temple Energized"],
    shortDesc: "Known as the Money Magnet stone. Shield yourself from evil eyes while attracting financial luck.",
    benefits: ["Shields Negative Energy", "Manifests Wealth", "Enhances Willpower"],
    size: "Adjustable Band",
    material: "Natural Raw Pyrite & Brass",
    useFor: ["Right Ring Finger", "Daily Wear"],
    stock: 60
  },
  {
    id: 6,
    slug: "shri-yantra-pure-brass-plate",
    name: "Shri Yantra Pure Brass Plate",
    subtitle: "Precision Vedic Engraved",
    category: "Yantra",
    purpose: "Laxmi Blessing",
    price: 3499,
    original: 4999,
    rating: 4.9,
    reviews: 340,
    img: "https://washi-custom-22412387.figma.site/_components/v2/0efc643709f6f883f69747b3c071474ddf94fb96/WhatsApp_Image_2026-07-04_at_20.51.30.b3cad81a.jpeg",
    badges: ["Handcrafted", "Vastu Approved"],
    shortDesc: "Holy Meru geometry that radiates Goddess Laxmi's permanent presence in home or office.",
    benefits: ["Corrects Vastu Dosh", "Increases Cash Flow", "Harmonizes Family Life"],
    size: "6 inch x 6 inch",
    material: "Solid Heavy Brass",
    useFor: ["Pooja Ghar", "Office Desk", "Cash Counter"],
    stock: 30
  },
  {
    id: 7,
    slug: "navratna-gemstone-pendant",
    name: "Navratna Gemstone Pendant",
    subtitle: "9 Planetary Alignment",
    category: "Gemstone",
    purpose: "Navagraha Shanti",
    price: 4999,
    original: 7499,
    rating: 4.9,
    reviews: 295,
    img: "https://cdn.shopify.com/s/files/1/0878/4907/4985/files/1-1_f53e2d9e-40a0-4f0e-95a9-8d6a878b2f77.webp?v=1781163169",
    badges: ["Certified Natural", "Masterpiece"],
    shortDesc: "Combines all nine astrological gemstones into a single harmonious sacred pendant.",
    benefits: ["Balances All 9 Planets", "Protection From Graha Dosh", "Brings Good Fortune"],
    size: "Medium Pendant",
    material: "9 Natural Gemstones & Silver",
    useFor: ["Necklace", "Special Poojas"],
    stock: 15
  }
];
